- docker-compose.yml
- docs/usage.md
> Added docker compose file to simplify launching Wanaku

- core/core-services/pom.xml
- core/core-services/src/main/java/ai/wanaku/core/services/config/WanakuProviderConfig.java
- core/core-services/src/main/java/ai/wanaku/core/services/config/WanakuServiceConfig.java
- core/core-services/src/main/java/ai/wanaku/core/services/provider/AbstractResourceDelegate.java
- core/core-services/src/main/java/ai/wanaku/core/services/util/URIHelper.java
- services/providers/wanaku-provider-file/src/main/java/ai/wanaku/provider/file/FileResourceDelegate.java
- services/providers/wanaku-provider-file/src/main/resources/application.properties
But require further improvements such as the one described on #64
> Rework to allow more flexibility with the file reading

- core/core-exchange/pom.xml
- core/core-services/pom.xml
- core/core-util/pom.xml
- parent/pom.xml
- pom.xml
- routers/pom.xml
- servers/wanaku-server-quarkus/pom.xml
- services/providers/wanaku-provider-file/pom.xml
- services/providers/wanaku-provider-ftp/pom.xml
- services/tools/wanaku-routing-http-service/pom.xml
- services/tools/wanaku-routing-kafka-service/pom.xml
- services/tools/wanaku-routing-yaml-route-service/pom.xml
> Cleanup dependency management

- core/core-services/src/test/java/ai/wanaku/core/services/util/URIHelperTest.java
- parent/pom.xml
- routers/wanaku-router/pom.xml
- routers/wanaku-router/src/main/java/ai/wanaku/routers/ToolsProvider.java
- routers/wanaku-router/src/main/java/ai/wanaku/routers/config/WanakuRouterConfig.java
- routers/wanaku-router/src/main/resources/application.properties
- routers/wanaku-router/src/test/java/ai/wanaku/routers/WanakuRouterMainTest.java
> Added some tools tests for the Wanaku Router

- README.md
- docs/usage.md
- Add link to the getting started video
- Adjust some getting started details
> Documentation improvements

- .gitignore
- api/src/main/java/ai/wanaku/api/exceptions/ResourceNotFoundException.java
- core/core-services/src/main/java/ai/wanaku/core/services/provider/AbstractResourceDelegate.java
- services/providers/wanaku-provider-s3/pom.xml
- services/providers/wanaku-provider-s3/src/main/assembly/assembly-native.xml
- services/providers/wanaku-provider-s3/src/main/assembly/assembly.xml
- services/providers/wanaku-provider-s3/src/main/java/ai/wanaku/provider/s3/ResourceService.java
- services/providers/wanaku-provider-s3/src/main/java/ai/wanaku/provider/s3/S3ResourceDelegate.java
- services/providers/wanaku-provider-s3/src/main/resources/application.properties
The S3 resource require the following configuration:
* Service link
```
wanaku targets resources link --service=aws2-s3 --target=localhost:9005
```
* Resource expose
```
wanaku resources expose --location=myBucket/myFile.txt --description="mySample resource added via CLI" --name="myS3 mcp via CLI" --type=aws2-s3
```
* Target resource configuration
```
wanaku targets resources configure --service=aws2-s3 --option=region --value=myAwsRegion 
wanaku targets resources configure --service=aws2-s3 --option=deleteAfterRead --value=false
wanaku targets resources configure --service=aws2-s3 --option=secretKey --value='RAW(mySecretKey)'
wanaku targets resources configure --service=aws2-s3 --option=accessKey --value=myAccessKey
```
> S3 Resource

- cli/src/main/assembly/assembly-native.xml
- routers/wanaku-router/src/main/assembly/assembly-native.xml
- services/providers/wanaku-provider-file/src/main/assembly/assembly-native.xml
- services/providers/wanaku-provider-ftp/src/main/assembly/assembly-native.xml
- services/providers/wanaku-provider-s3/src/main/assembly/assembly-native.xml
- services/tools/wanaku-routing-http-service/src/main/assembly/assembly-native.xml
- services/tools/wanaku-routing-kafka-service/src/main/assembly/assembly-native.xml
- services/tools/wanaku-routing-yaml-route-service/src/main/assembly/assembly-native.xml
> Fixed incorrect generation of the assembly in native build mode

- core/core-exchange/src/main/java/ai/wanaku/core/exchange/ParsedToolInvokeRequest.java
- routers/wanaku-router/src/main/java/ai/wanaku/routers/proxies/tools/Request.java
> Fix not normalizing URLs correctly

- ui/package.json
- ui/src/App.scss
- ui/src/App.tsx
- ui/src/Pages/LLMChat/LLMChatPage.tsx
- ui/src/Pages/LLMChat/index.ts
- ui/src/Pages/LLMChat/router-exports.tsx
- ui/src/Pages/Resources/ResourcesPage.tsx
- ui/src/Pages/Tools/ToolsPage.tsx
- ui/src/router.tsx
- ui/src/router/links.models.ts
- ui/tsconfig.app.json
- ui/yarn.lock
> issue #89 developer tab: LLM chat to test MCP tools

- jreleaser.yml
- services/tools/wanaku-routing-http-service/pom.xml
- services/tools/wanaku-routing-yaml-route-service/pom.xml
> Disable native mode for unsupported services

- servers/wanaku-server-quarkus/src/main/java/ai/wanaku/server/quarkus/api/v1/resources/ResourcesBean.java
- servers/wanaku-server-quarkus/src/test/java/ai/wanaku/server/quarkus/api/v1/resources/ResourcesResourceTest.java
> Correctly remove resources

- cli/src/main/java/ai/wanaku/cli/main/CliMain.java
- cli/src/main/java/ai/wanaku/cli/main/commands/services/Services.java
- cli/src/main/java/ai/wanaku/cli/main/commands/services/ServicesBase.java
- cli/src/main/java/ai/wanaku/cli/main/commands/services/ServicesCreate.java
- cli/src/main/java/ai/wanaku/cli/main/commands/services/ServicesCreateResources.java
- cli/src/main/java/ai/wanaku/cli/main/commands/services/ServicesCreateTool.java
- cli/src/main/java/ai/wanaku/cli/main/support/WanakuCliConfig.java
- cli/src/main/resources/application.properties
- core/core-util/src/main/java/ai/wanaku/core/util/ProcessRunner.java
- docs/usage.md
> Simplify creating downstream services

- archetypes/wanaku-provider-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
- archetypes/wanaku-provider-archetype/src/main/resources/archetype-resources/pom.xml
- archetypes/wanaku-tool-service-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
- archetypes/wanaku-tool-service-archetype/src/main/resources/archetype-resources/pom.xml
- cli/src/main/java/ai/wanaku/cli/main/commands/services/ServicesBase.java
- core/core-runtimes/core-runtime-camel/pom.xml
- core/core-runtimes/core-runtime-camel/src/main/java/ai/wanaku/core/runtime/camel/DefaultResourceConsumer.java
- core/core-runtimes/core-runtime-camel/src/main/java/ai/wanaku/core/runtime/camel/EndpointOptions.java
- core/core-runtimes/pom.xml
- core/core-services/pom.xml
- core/core-services/src/main/java/ai/wanaku/core/services/common/ServiceOptions.java
- core/core-services/src/main/java/ai/wanaku/core/services/provider/AbstractResourceDelegate.java
- core/pom.xml
- docs/contributing.md
- services/providers/wanaku-provider-file/pom.xml
- services/providers/wanaku-provider-ftp/pom.xml
- services/providers/wanaku-provider-ftp/src/main/java/ai/wanaku/provider/ftp/FTPResourceDelegate.java
- services/providers/wanaku-provider-s3/pom.xml
- services/providers/wanaku-provider-s3/src/main/java/ai/wanaku/provider/s3/S3ResourceDelegate.java
- services/tools/wanaku-routing-http-service/pom.xml
- services/tools/wanaku-routing-kafka-service/pom.xml
- services/tools/wanaku-routing-tavily-service/pom.xml
- services/tools/wanaku-routing-yaml-route-service/pom.xml
This simplifies adding Java runtimes that don't leverage Camel. This resolves issue #189
> Decouple the runtime from the service

- routers/wanaku-router/src/main/resources/application.properties
- servers/wanaku-server-quarkus/src/main/resources/application.properties
> Fix UI running only on localhost

- core/core-exchange/src/main/java/ai/wanaku/core/exchange/ParsedToolInvokeRequest.java
- core/core-util/src/main/java/ai/wanaku/core/uri/Parameter.java
- core/core-util/src/main/java/ai/wanaku/core/util/ProcessRunner.java
- core/core-util/src/test/java/ai/wanaku/core/uri/URIParserTest.java
- docs/usage.md
- services/tools/pom.xml
- services/tools/wanaku-routing-exec-service/README.md
- services/tools/wanaku-routing-exec-service/pom.xml
- services/tools/wanaku-routing-exec-service/src/main/assembly/assembly-native.xml
- services/tools/wanaku-routing-exec-service/src/main/assembly/assembly.xml
- services/tools/wanaku-routing-exec-service/src/main/java/ai/wanaku/routing/service/ExecClient.java
- services/tools/wanaku-routing-exec-service/src/main/java/ai/wanaku/routing/service/ExecDelegate.java
- services/tools/wanaku-routing-exec-service/src/main/java/ai/wanaku/routing/service/InvocationService.java
- services/tools/wanaku-routing-exec-service/src/main/resources/application.properties
Comes bundled with a few fixes
> Add a new Exec service

- Makefile
- samples/routes/camel-route/camel-jbang-quote.camel.yaml
- services/tools/wanaku-routing-exec-service/README.md
- tests/basic-test/basic-test.py
> Enable running Camel JBang via the exec service

- cli/pom.xml
- cli/src/main/java/ai/wanaku/cli/main/CliMain.java
- cli/src/main/java/ai/wanaku/cli/main/commands/start/Start.java
- cli/src/main/java/ai/wanaku/cli/main/commands/start/StartBase.java
- cli/src/main/java/ai/wanaku/cli/main/commands/start/StartLocal.java
- cli/src/main/java/ai/wanaku/cli/main/support/Downloader.java
- cli/src/main/java/ai/wanaku/cli/main/support/RuntimeConstants.java
- cli/src/main/java/ai/wanaku/cli/main/support/WanakuCliConfig.java
- cli/src/main/java/ai/wanaku/cli/main/support/ZipHelper.java
- cli/src/main/java/ai/wanaku/cli/runner/local/LocalRunner.java
- cli/src/main/java/ai/wanaku/cli/types/Container.java
- cli/src/main/java/ai/wanaku/cli/types/Environment.java
- cli/src/main/java/ai/wanaku/cli/types/Service.java
- cli/src/main/java/ai/wanaku/cli/types/WanakuDeployment.java
- cli/src/main/resources/application.properties
- cli/src/main/resources/services-default.json
- core/core-util/src/main/java/ai/wanaku/core/util/ProcessRunner.java
- docs/usage.md
> Simplify getting started experience

- docs/usage.md
- jbang-catalog.json
- jbang/pom.xml
- jbang/src/main/java/ai/wanaku/jbang/WanakuJBang.java
- pom.xml
Ensure you have local 0.0.4-SNAPSHOT build, then you can try to run it with 
```
jbang run -Dwanaku.version=0.0.4-SNAPSHOT wanaku@llowinge/wanaku/jbang-support start local
```
If you will be OK with this approach, i'll also add some basic readme how to run it.
> [closes #215] Add JBang support

- pom.xml
Made following changes to the POM.xml file to resolve the issue
1.  JReleaser plugin is added in the parent "POM.xml" under the <pluginManagement> section.
2.  Added "jreleaser-maven-plugin.version" property is set corrected "pom.xml"
> issue: Automate release with jreleaser and Maven #90

- core/core-persistence/core-persistence-api/src/main/java/ai/wanaku/core/persistence/api/WanakuRepository.java
- core/core-persistence/core-persistence-file/src/main/java/ai/wanaku/core/persistence/file/AbstractFileRepository.java
- core/core-persistence/core-persistence-mongodb/src/main/java/ai/wanaku/core/persistence/mongodb/AbstractMongoDBRepository.java
- routers/wanaku-router/src/main/webui/openapi.json
- routers/wanaku-router/src/main/webui/openapi.yaml
- servers/wanaku-server-quarkus/src/main/java/ai/wanaku/server/quarkus/api/v1/forwards/ForwardsBean.java
- servers/wanaku-server-quarkus/src/main/java/ai/wanaku/server/quarkus/api/v1/forwards/ForwardsResource.java
- servers/wanaku-server-quarkus/src/main/java/ai/wanaku/server/quarkus/api/v1/resources/ResourcesBean.java
- servers/wanaku-server-quarkus/src/main/java/ai/wanaku/server/quarkus/api/v1/resources/ResourcesResource.java
- servers/wanaku-server-quarkus/src/main/java/ai/wanaku/server/quarkus/api/v1/tools/ToolsBean.java
- servers/wanaku-server-quarkus/src/main/java/ai/wanaku/server/quarkus/api/v1/tools/ToolsResource.java
- ui/src/api/wanaku-router-api.ts
> Added a new API for updating resources, tools and forwards

- services/tools/pom.xml
- services/tools/wanaku-tool-service-sqs/README.md
- services/tools/wanaku-tool-service-sqs/pom.xml
- services/tools/wanaku-tool-service-sqs/src/main/assembly/assembly-native.xml
- services/tools/wanaku-tool-service-sqs/src/main/assembly/assembly.xml
- services/tools/wanaku-tool-service-sqs/src/main/java/ai/wanaku/tool/InvocationService.java
- services/tools/wanaku-tool-service-sqs/src/main/java/ai/wanaku/tool/SQSClient.java
- services/tools/wanaku-tool-service-sqs/src/main/java/ai/wanaku/tool/SQSDelegate.java
- services/tools/wanaku-tool-service-sqs/src/main/resources/application.properties
- services/tools/wanaku-tool-service-sqs/src/main/resources/reflection-config.json
> Added Wanaku SQS tool

- services/tools/wanaku-tool-service-sqs/README.md
- services/tools/wanaku-tool-service-sqs/src/main/java/ai/wanaku/tool/sqs/SQSClient.java
- services/tools/wanaku-tool-service-sqs/src/main/resources/application.properties
- Ajust the request queue so that the request URI with the queueOrArn is not dependent on the user
- Document
> Adjust SQS

- core/core-persistence/core-persistence-file/src/main/java/ai/wanaku/core/persistence/file/FileServiceRegistry.java
- core/core-persistence/core-persistence-file/src/test/java/ai/wanaku/core/persistence/file/ServiceRegistryTest.java
> Ensure that configurations persist on service reboot

- services/tools/wanaku-tool-service-kafka/README.md
- services/tools/wanaku-tool-service-kafka/src/main/java/ai/wanaku/tool/kafka/KafkaClient.java
> Make Kafka behavior consistent with SQS

- docs/usage.md
Add instructions for using Wanaku as an MCP Server with Claude Desktop
> Add instructions for Claude Desktop configuration

- core/core-persistence/core-persistence-infinispan/src/main/java/ai/wanaku/core/persistence/infinispan/providers/InfinispanConfigurationProvider.java
> Make sure to create the data directory if it does not exist

- core/core-services/src/main/java/ai/wanaku/core/services/config/WanakuServiceConfig.java
- core/core-services/src/main/java/ai/wanaku/core/services/provider/AbstractResourceDelegate.java
- core/core-services/src/main/java/ai/wanaku/core/services/tool/AbstractToolDelegate.java
- docs/usage.md
- services/tools/wanaku-tool-service-http/src/main/resources/application.properties
> Allow adjusting the announcement address

- docker-compose.yml
> Router is not creating its data directory #318

- ui/src/App.tsx
- ui/src/Pages/Targets/ServiceTargetState.ts
- ui/src/Pages/Targets/TargetsPage.tsx
- ui/src/Pages/Targets/TargetsTable.tsx
- ui/src/Pages/Targets/index.ts
- ui/src/Pages/Targets/router-exports.tsx
- ui/src/hooks/api/use-targets.ts
- ui/src/router.tsx
- ui/src/router/links.models.ts
> Targets page

- deploy/openshift/wanaku-tool-service-http.yaml
- docker-compose-prod.yml
- docker-compose.yml
> Ensure containers use the newer settings format

- capabilities/tools/wanaku-tool-service-yaml-route/src/main/java/ai/wanaku/tool/yaml/route/InvocationService.java
> Reduce the incidence of blocking warnings for slower routes

- cli/pom.xml
> Stop building containers for the CLI as they are buggy
